#!/usr/bin/env python

import sys, os

sys.path.insert(1, './Speed/')
import ngl_s_g as TS

def _writefile(fname,src):
    with open(fname,'w') as writer:
        writer.write(src.replace('\n\n','\n'))

if len(sys.argv) > 1:
    fname = sys.argv[1] # File which has NGL Speed code
else:
    fname = 'test.ngls'
wfile = 'work.py' # File to store NGL code

ast = TS.translate(fname)
python = ast.as_python()
_writefile(wfile, python)

